(() => {
  const { key, s } = window.__portfolio;
  try { if (typeof raf !== "undefined") cancelAnimationFrame(raf); } catch {}

  const pages = [
    ["home", "Home"], ["about", "About"], ["expertise", "Expertise"],
    ["experience", "Experience"], ["projects", "Projects"], ["process", "Process"],
    ["impact", "Impact"], ["certifications", "Credentials"], ["insights", "Insights"],
    ["testimonials", "References"], ["contact", "Contact"]
  ];
  const heroFiles = {"ai-ml":"ai-ml.png","data-scientist":"data-scientist.png",cloud:"cloud.png",cyber:"cyber.png",software:"software.png",product:"product.png",designer:"designer.png",devops:"devops.png",fullstack:"fullstack.png",analyst:"analyst.png"};
  const profiles = {
    "ai-ml": {identity:"Applied intelligence, production discipline", focus:["Model evaluation and observability","Retrieval and ranking systems","Responsible AI guardrails","Low-latency inference"], domains:["Generative AI","Recommendation","Computer vision","Healthcare ML"], process:["Frame the decision","Build the baseline","Measure failure modes","Productionize safely","Monitor reality"], fit:"Teams moving machine learning from promising demo to dependable product.", signal:"MODEL / EVALUATE / OPERATE"},
    "data-scientist": {identity:"Evidence, experiments, decisions", focus:["Causal inference","Forecasting systems","Experiment design","Decision storytelling"], domains:["Growth science","Demand planning","Customer analytics","Product experimentation"], process:["Clarify the decision","Audit the evidence","Model uncertainty","Test the intervention","Communicate the choice"], fit:"Teams that need analytical rigor without losing delivery momentum.", signal:"QUESTION / MODEL / DECIDE"},
    cloud: {identity:"Resilience designed before scale arrives", focus:["Landing-zone architecture","Platform reliability","FinOps governance","Cloud security patterns"], domains:["Multi-cloud","Regulated systems","Kubernetes platforms","Legacy modernization"], process:["Map constraints","Model failure","Design boundaries","Automate delivery","Prove recovery"], fit:"Organizations modernizing critical workloads without gambling on reliability.", signal:"DESIGN / AUTOMATE / RECOVER"},
    cyber: {identity:"Practical defense, calm response", focus:["Detection engineering","Adversary simulation","Incident readiness","Identity security"], domains:["Cloud threats","Application security","Network defense","Security operations"], process:["Model the threat","Find the path","Prioritize exposure","Close the gap","Practice response"], fit:"Teams that want measurable security outcomes instead of security theatre.", signal:"ANTICIPATE / DETECT / RESPOND"},
    software: {identity:"Clear systems that age well", focus:["Frontend architecture","Service design","Developer experience","Quality engineering"], domains:["Collaborative software","Design systems","Real-time products","API platforms"], process:["Understand the behavior","Shape the boundary","Build the thin path","Test the contract","Refine the system"], fit:"Product teams that value shipping speed and long-term code clarity equally.", signal:"MODEL / BUILD / REFINE"},
    product: {identity:"Customer truth turned into momentum", focus:["Product strategy","Discovery systems","Growth experiments","Cross-functional delivery"], domains:["B2B SaaS","Activation","Collaboration","Platform products"], process:["Name the outcome","Study the behavior","Choose the bet","Align the team","Measure the change"], fit:"Teams navigating ambiguity, competing priorities, and meaningful growth goals.", signal:"DISCOVER / ALIGN / SHIP"},
    designer: {identity:"Complexity made calm and human", focus:["Interaction design","User research","Design systems","Service blueprints"], domains:["Healthcare","Fintech","Collaboration","Enterprise UX"], process:["Listen closely","Map the system","Explore widely","Prototype reality","Refine with evidence"], fit:"Teams solving consequential workflows where clarity and trust matter.", signal:"UNDERSTAND / SHAPE / PROVE"},
    devops: {identity:"The safest path becomes the fastest path", focus:["Developer platforms","CI/CD architecture","Infrastructure as code","Observability systems"], domains:["Kubernetes","GitOps","Cloud platforms","Site reliability"], process:["Observe the flow","Remove the toil","Codify the path","Guard the release","Learn from production"], fit:"Engineering organizations ready to turn delivery friction into platform leverage.", signal:"BUILD / VERIFY / RELEASE"},
    fullstack: {identity:"One product, every layer considered", focus:["Product interfaces","API architecture","Data modeling","Performance engineering"], domains:["Real-time apps","Marketplaces","Analytics products","Workflow software"], process:["Trace the journey","Model the data","Connect the seams","Ship vertically","Tune with evidence"], fit:"Small, ambitious teams that need end-to-end ownership without handoff gaps.", signal:"INTERFACE / SERVICE / DATA"},
    analyst: {identity:"Operational clarity people can act on", focus:["BI architecture","Metric governance","Data modeling","Executive reporting"], domains:["Operations","Finance analytics","Supply chain","Revenue intelligence"], process:["Define the metric","Reconcile the source","Model the logic","Design the decision","Enable the team"], fit:"Operational teams that need one trusted view and faster, better decisions.", signal:"RECONCILE / EXPLAIN / ACT"}
  };
  const p = profiles[key] || {identity:`${s.role} · thoughtful delivery`,focus:s.skills.slice(0,4).map(x=>x[0]),domains:[s.skills[0][0],s.skills[1][0],"Cross-functional delivery","High-stakes decisions"],process:["Clarify the outcome","Map the context","Choose the approach","Deliver with care","Measure the result"],fit:`Teams looking for a ${s.role.toLowerCase()} who combines practical judgment with clear communication.`,signal:"UNDERSTAND / DELIVER / IMPROVE"};
  const icon = name => {
    const paths = {
      moon:'<path d="M20 15.2A8.5 8.5 0 1 1 8.8 4a7 7 0 0 0 11.2 11.2Z"/>',
      sun:'<circle cx="12" cy="12" r="4"/><path d="M12 2v2M12 20v2M4.93 4.93l1.42 1.42M17.65 17.65l1.42 1.42M2 12h2M20 12h2M4.93 19.07l1.42-1.42M17.65 6.35l1.42-1.42"/>',
      menu:'<path d="M4 7h16M4 12h16M4 17h16"/>', close:'<path d="m6 6 12 12M18 6 6 18"/>',
      arrow:'<path d="M5 12h14M14 7l5 5-5 5"/>', mail:'<rect x="3" y="5" width="18" height="14" rx="2"/><path d="m3 7 9 6 9-6"/>'
    };
    return `<svg class="v2-icon" viewBox="0 0 24 24" aria-hidden="true">${paths[name]}</svg>`;
  };
  const esc = value => String(value).replace(/[&<>"']/g, char => ({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#039;"}[char]));
  const route = () => {
    const value = new URLSearchParams(location.search).get("page") || "home";
    return pages.some(([id]) => id === value) ? value : "home";
  };
  const link = (id, label) => `<a href="#${id}" data-route="${id}">${label}</a>`;
  const pageHead = (title, copy) => `<header class="v2-inner-hero v2-reveal"><h1>${title}</h1><p>${copy}</p></header>`;
  const chips = items => `<div class="v2-chips">${items.map(x=>`<span class="v2-chip">${x}</span>`).join("")}</div>`;
  const heroMotion = () => ({
    "ai-ml": `<div class="role-motion motion-ai" aria-hidden="true"><i class="ai-link l1"></i><i class="ai-link l2"></i><i class="ai-link l3"></i>${Array.from({length:9},(_,i)=>`<i class="ai-node n${i+1}"></i>`).join("")}</div>`,
    "data-scientist": `<div class="role-motion motion-data" aria-hidden="true"><i class="data-stream s1"></i><i class="data-stream s2"></i><i class="data-stream s3"></i><div class="data-bars">${[40,68,52,86,70].map((h,i)=>`<i style="--bar:${h}%;--delay:${i*120}ms"></i>`).join("")}</div></div>`,
    cloud: `<div class="role-motion motion-cloud" aria-hidden="true"><i class="cloud-link c1"></i><i class="cloud-link c2"></i><i class="cloud-link c3"></i><i class="cloud-node cn1"></i><i class="cloud-node cn2"></i><i class="cloud-node cn3"></i><i class="cloud-node cn4"></i></div>`,
    cyber: `<div class="role-motion motion-cyber" aria-hidden="true"><i class="cyber-ring r1"></i><i class="cyber-ring r2"></i><i class="cyber-ring r3"></i><i class="cyber-sweep"></i><i class="cyber-core"></i></div>`,
    software: `<div class="role-motion motion-software" aria-hidden="true"><div class="code-stack">${Array.from({length:8},(_,i)=>`<i class="code-line q${i+1}"></i>`).join("")}</div><i class="commit-path"></i>${[1,2,3,4,5].map(i=>`<i class="commit-dot d${i}"></i>`).join("")}</div>`,
    product: `<div class="role-motion motion-product" aria-hidden="true"><i class="road-line"></i><div class="road-card rc1"></div><div class="road-card rc2"></div><div class="road-card rc3"></div><i class="ship-target"></i></div>`,
    designer: `<div class="role-motion motion-designer" aria-hidden="true"><i class="wire-card w1"></i><i class="wire-card w2"></i><i class="wire-card w3"></i><i class="final-card f1"></i><i class="final-card f2"></i></div>`,
    devops: `<div class="role-motion motion-devops" aria-hidden="true"><i class="pipe-line"></i><i class="pipe-stage ps1"></i><i class="pipe-stage ps2"></i><i class="pipe-stage ps3"></i><i class="pipe-package"></i></div>`,
    fullstack: `<div class="role-motion motion-fullstack" aria-hidden="true"><div class="front-layer fl1"></div><div class="front-layer fl2"></div><div class="back-layer bl1"></div><div class="back-layer bl2"></div><i class="stack-link"></i></div>`,
    analyst: `<div class="role-motion motion-analyst" aria-hidden="true"><div class="analyst-bars">${[36,64,50,82,70,92].map((h,i)=>`<i style="--bar:${h}%;--delay:${i*90}ms"></i>`).join("")}</div><i class="analyst-line al1"></i><i class="analyst-line al2"></i></div>`
  }[key] || `<div class="role-motion motion-executive" aria-hidden="true"><i class="exec-ring er1"></i><i class="exec-ring er2"></i><i class="exec-signal es1"></i><i class="exec-signal es2"></i><i class="exec-signal es3"></i><i class="exec-core"></i></div>`);
  const cinema = {
    "ai-ml": ["Signals become judgment.","INGEST / TRAIN / OPERATE","Raw signal · Model confidence · Reliable decisions"],
    "data-scientist": ["Evidence, made legible.","COLLECT / MODEL / EXPLAIN","Messy evidence · Clear model · Decisions people trust"],
    cloud: ["Architecture at altitude.","MAP / ORCHESTRATE / SCALE","Distributed systems · Resilient routes · Quiet scale"],
    cyber: ["Calm inside the perimeter.","DETECT / ISOLATE / HARDEN","Weak signal · Defensive response · Durable control"],
    software: ["From a thought to a system.","SHAPE / BUILD / SHIP","Working code · Intentional releases · Systems that last"],
    product: ["Momentum, with a point.","FRAME / ALIGN / DELIVER","A hard problem · Team alignment · Measurable movement"],
    designer: ["Interfaces that earn attention.","OBSERVE / COMPOSE / REFINE","A human need · A clear interface · A finished feeling"],
    devops: ["Release confidence in motion.","BUILD / VERIFY / DEPLOY","One commit · Continuous proof · A stable release"],
    fullstack: ["Every layer in conversation.","CONNECT / COMPOSE / PERFORM","Interface intent · System response · One coherent product"],
    analyst: ["The story inside the signal.","QUESTION / REVEAL / ACT","A useful question · A visible pattern · A better decision"]
  };
  const cinematic = () => { const [headline,sequence,beats]=cinema[key] || [`${s.role} with purpose.`,`UNDERSTAND / DELIVER / IMPROVE`,`Clear context · Decisive action · Lasting value`]; const [a,b,c]=beats.split(" · "); return `<section class="v2-cinematic" data-cinematic="${key}"><div class="cine-stage"><div class="cine-art" aria-hidden="true"></div><div class="cine-grain" aria-hidden="true"></div><div class="cine-grid" aria-hidden="true"></div><div class="cine-orbit orbit-one" aria-hidden="true"></div><div class="cine-orbit orbit-two" aria-hidden="true"></div><div class="cine-role-visual" aria-hidden="true">${heroMotion()}</div><div class="cine-copy"><p class="cine-kicker">${sequence}</p><h1>${headline.split(" ").slice(0,-1).join(" ")} <em>${headline.split(" ").slice(-1)}</em></h1><p>${s.intro}</p><div class="cine-actions"><a class="cine-button" href="#projects" data-route="projects">Enter the work ${icon("arrow")}</a><span>Scroll to direct the sequence</span></div></div><div class="cine-beats" aria-label="Role story"><div><b>01</b><span>${a}</span></div><div><b>02</b><span>${b}</span></div><div><b>03</b><span>${c}</span></div></div><div class="cine-meter" aria-hidden="true"><i></i></div></div></section>`; };
  const home = () => `${cinematic()}<div class="v2-wrap"><section class="v2-hero v2-after-cinematic"><div class="v2-hero-copy"><div class="v2-status"><i></i>Open to the right ambitious team</div><h1>${s.tag.split(" ").slice(0,-2).join(" ")} <em>${s.tag.split(" ").slice(-2).join(" ")}</em></h1><p class="v2-deck">${s.intro} ${p.fit}</p><div class="v2-cta"><a class="v2-btn" href="#projects" data-route="projects">Explore case studies ${icon("arrow")}</a><a class="v2-btn secondary" href="#contact" data-route="contact">Discuss a role</a></div></div><div class="v2-hero-art" data-tilt>${heroMotion()}<div class="v2-float-panel"><strong>${p.identity}</strong><span>${p.signal}</span></div></div></section><section class="v2-proof">${s.facts.map(x=>`<div class="v2-reveal"><strong>${x[0]}</strong><span>${x[1]}</span></div>`).join("")}</section><section class="v2-section"><h2 class="v2-reveal">What a hiring team gets on day one.</h2><div class="v2-grid">${p.focus.map((x,i)=>`<article class="v2-panel ${i===0?'span-8 feature':'span-4'} v2-reveal"><span class="v2-big-number">0${i+1}</span><h3>${x}</h3><p>${["A defined approach, clear trade-offs, and an operating model the team can own.","Evidence translated into a decision, not another report to interpret.","Senior-level collaboration across product, design, engineering, and operations.","A bias toward durable systems with measurable impact."][i]}</p></article>`).join("")}</div></section><section class="v2-section"><h2 class="v2-reveal">Selected proof, not a gallery of output.</h2><div class="v2-grid">${s.projects.slice(0,2).map((x,i)=>caseCard(x,i,"span-6")).join("")}</div></section></div>`;
  const about = () => `<div class="v2-wrap">${pageHead(`The person behind<br>${p.identity.toLowerCase()}.`,`${s.name} is a ${s.role} who works where ambiguity, systems thinking, and accountable delivery meet.`)}<section class="v2-section"><div class="v2-grid"><article class="v2-panel span-7 feature v2-reveal"><h2>A short professional story.</h2><p>${s.intro} Across the last several years, the consistent thread has been turning complicated conditions into a path teams can understand, execute, and improve.</p></article><article class="v2-panel span-5 v2-reveal"><h3>Best environment</h3><p>${p.fit}</p>${chips(p.domains)}</article><article class="v2-panel span-4 v2-reveal"><h3>How I lead</h3><p>Make the problem visible. Invite the right disagreement. Commit clearly. Learn without blame.</p></article><article class="v2-panel span-4 v2-reveal"><h3>How I communicate</h3><p>Concise when the decision is simple, detailed when the risk is real, and always explicit about uncertainty.</p></article><article class="v2-panel span-4 v2-reveal"><h3>What I optimize</h3><p>Customer value, team agency, operational clarity, and systems that improve after launch.</p></article></div></section></div>`;
  const expertise = () => `<div class="v2-wrap">${pageHead("Depth where the work gets difficult.",`A practical capability map for ${s.role.toLowerCase()} work, grounded in delivery rather than tool collecting.`)}<section class="v2-section"><h2 class="v2-reveal">Core capability</h2><div class="v2-grid">${s.skills.map(x=>`<article class="v2-panel v2-skill v2-reveal"><div><h3>${x[0]}</h3><p>${p.focus[x[0].length%p.focus.length]}</p></div><strong>${x[1]}</strong><div class="v2-skill-meter"><i style="--level:${x[1]}%"></i></div></article>`).join("")}</div></section><section class="v2-section"><h2 class="v2-reveal">Working domains</h2><div class="v2-grid">${p.domains.map((x,i)=>`<article class="v2-panel span-6 v2-reveal"><span class="v2-big-number">${String(i+1).padStart(2,"0")}</span><h3>${x}</h3><p>Hands-on patterns, constraints, and decision frameworks developed through realistic sample engagements.</p></article>`).join("")}</div></section></div>`;
  const experience = () => `<div class="v2-wrap">${pageHead("Experience that compounds.","Roles, responsibilities, and the changes left behind after the work shipped.")}<section class="v2-section"><div class="v2-list">${s.jobs.map((x,i)=>`<article class="v2-row v2-reveal"><time>${x[0]}</time><div><h3>${x[1]}</h3><p>${x[2]} ${["Set the operating standard, coached senior contributors, and connected strategy to measurable execution.","Built reusable systems that raised quality while reducing repeated delivery effort.","Developed the hands-on foundation for clear technical judgment and cross-functional trust."][i]}</p>${chips([p.domains[i%p.domains.length],p.focus[i%p.focus.length]])}</div><small>0${i+1}</small></article>`).join("")}</div></section><section class="v2-section"><blockquote class="v2-quote v2-reveal">“${s.quotes[0][0]}”<small>${s.quotes[0][1]}</small></blockquote></section></div>`;
  const caseCard = (x,i,span="") => `<article class="v2-panel v2-case ${span} v2-reveal"><div class="v2-case-art" style="background-position:${60+i*12}% center"></div><div class="v2-case-body"><h3>${x[0]}</h3><p>${x[1]}</p><div class="v2-chips">${chips([x[2],x[3],"Sample case study"])}</div></div></article>`;
  const projects = () => `<div class="v2-wrap">${pageHead("Case studies with decisions inside.","Each story covers the problem, the reasoning, the collaboration, and the measurable outcome, not only the final artifact.")}<section class="v2-section"><div class="v2-grid">${s.projects.map((x,i)=>caseCard(x,i)).join("")}</div></section><section class="v2-section"><div class="v2-panel span-12 feature v2-reveal"><h2>What the portfolio can discuss live.</h2><p>Architecture choices, rejected alternatives, stakeholder tension, delivery constraints, measurement quality, and what I would change with another iteration.</p></div></section></div>`;
  const process = () => `<div class="v2-wrap">${pageHead("A process designed to create momentum.","Enough structure to reduce risk, enough flexibility to respond when the evidence changes.")}<section class="v2-section"><div class="v2-process">${p.process.map((x,i)=>`<article class="v2-step v2-reveal"><b>${i+1}</b><h3>${x}</h3><p>${["Align on the decision, constraints, and definition of done.","Gather the minimum evidence needed to choose intelligently.","Make the system and trade-offs visible to the whole team.","Ship a narrow, valuable path with quality built in.","Measure reality, document learning, and improve the system."][i]}</p></article>`).join("")}</div></section><section class="v2-section"><div class="v2-grid"><article class="v2-panel span-6 v2-reveal"><h3>Collaboration rhythm</h3><p>Working sessions for hard decisions, asynchronous artifacts for context, and concise checkpoints that protect maker time.</p></article><article class="v2-panel span-6 v2-reveal"><h3>Decision quality</h3><p>Assumptions are named, reversibility is considered, and success measures are agreed before output becomes expensive.</p></article></div></section></div>`;
  const impact = () => `<div class="v2-wrap">${pageHead("Impact that survives the presentation.","A recruiter-ready view of business outcomes, operational leverage, and the systems that made the change repeatable.")}<section class="v2-section"><div class="v2-grid">${s.facts.map((x,i)=>`<article class="v2-panel ${i===0?'span-7 feature':'span-5'} v2-reveal"><strong class="v2-big-number">${x[0]}</strong><span class="v2-label">${x[1]}</span><p>${["Primary outcome created through focused diagnosis, cross-functional execution, and measurable follow-through.","Scale handled without trading away clarity, reliability, or team ownership.","A repeatable capability left behind, not a one-off heroic effort.","Experience applied with judgment appropriate to the operating context."][i]}</p></article>`).join("")}</div></section><section class="v2-section"><h2 class="v2-reveal">How impact is measured.</h2><div class="v2-grid">${["Customer behavior","Business performance","Operational health","Team leverage"].map(x=>`<article class="v2-panel span-6 v2-reveal"><h3>${x}</h3><p>Leading and lagging indicators are paired so the team can act early without confusing activity for outcome.</p></article>`).join("")}</div></section></div>`;
  const certifications = () => `<div class="v2-wrap">${pageHead("Credentials, backed by application.","Formal learning matters most when it changes the quality of real decisions and implementation.")}<section class="v2-section"><div class="v2-list">${s.badges.map((x,i)=>`<article class="v2-row v2-reveal"><time>${2022+i}</time><div><h3>${x}</h3><p>Verified sample credential demonstrating structured knowledge in ${p.focus[i%p.focus.length].toLowerCase()}, with principles applied across portfolio case work.</p></div><small>Verified sample</small></article>`).join("")}</div></section><section class="v2-section"><div class="v2-panel span-12 feature v2-reveal"><h2>Current learning edge</h2><p>Deepening practical fluency in ${p.domains.join(", ").toLowerCase()}, with a focus on decisions that affect reliability, customer trust, and delivery speed.</p></div></section></div>`;
  const insights = () => { const titles=[`The hidden cost of unclear ${s.role.toLowerCase()} decisions`,`What strong teams measure before they scale`,`A practical guide to reversible architecture`,`Why operating models outlast roadmaps`,`The questions I ask in the first ten days`,`How to communicate uncertainty without losing momentum`]; return `<div class="v2-wrap">${pageHead("Thinking made useful.","Short field notes for hiring teams and practitioners who care about better decisions, not louder opinions.")}<section class="v2-section"><div class="v2-grid">${titles.map((x,i)=>`<article class="v2-panel span-6 v2-reveal"><small class="v2-chip">${p.domains[i%p.domains.length]}</small><h3>${x}</h3><p>${["A clear framework for spotting the issue early and giving the team a better option.","Observations from realistic delivery conditions, with the trade-offs left visible."][i%2]}</p><span class="v2-label">${4+i} minute read · Sample article</span></article>`).join("")}</div></section></div>`; };
  const testimonials = () => `<div class="v2-wrap">${pageHead("What collaboration feels like.","Sample references focused on judgment, communication, ownership, and the quality of the working relationship.")}<section class="v2-section">${s.quotes.map(x=>`<blockquote class="v2-quote v2-reveal">“${x[0]}”<small>${x[1]}</small></blockquote>`).join("")}</section><section class="v2-section"><h2 class="v2-reveal">Working agreements</h2><div class="v2-grid">${["No surprise decisions","Direct, respectful feedback","Context before ceremony","Ownership after launch"].map(x=>`<article class="v2-panel span-6 v2-reveal"><h3>${x}</h3><p>Clear expectations reduce coordination cost and make room for stronger individual judgment.</p></article>`).join("")}</div></section></div>`;
  const contact = () => `<div class="v2-wrap">${pageHead("Start with the real challenge.",`Hiring for ${s.role.toLowerCase()} leadership or planning a focused collaboration? Share the context, constraints, and outcome.`)}<section class="v2-section"><div class="v2-grid"><div class="v2-panel span-5 feature v2-reveal"><h2>Availability</h2><p>Open to senior full-time roles, focused advisory work, and high-leverage collaborations. Typical reply within two business days.</p>${chips(["Remote friendly","Sample portfolio","References available"])}</div><form class="v2-panel span-7 v2-form v2-reveal" id="v2-form"><label class="v2-field">Name<input name="name" autocomplete="name" required></label><label class="v2-field">Work email<input type="email" name="email" autocomplete="email" required></label><label class="v2-field full">Role or project context<input name="context" required></label><label class="v2-field full">What should success look like?<textarea name="message" required></textarea></label><div class="v2-field full"><button class="v2-btn" type="submit">Prepare message ${icon("mail")}</button><span id="v2-form-status" aria-live="polite"></span></div></form></div></section></div>`;
  const renderers = {home,about,expertise,experience,projects,process,impact,certifications,insights,testimonials,contact};

  document.body.className = "v2";
  document.body.dataset.role = key;
  if(window.extraSites?.[key]){const portraitIndex=Object.keys(window.extraSites).indexOf(key),palettes=[["#e4b05c","#6b7cff"],["#5cd6c3","#e4b05c"],["#8caeff","#d7a4ff"],["#c59cff","#e4b05c"],["#64e0d0","#73a8ff"],["#6cb7ff","#82e6a5"],["#e1b160","#9bb6ff"],["#6be2ab","#64a5ff"],["#82aafc","#e6bb73"],["#fa7aa6","#8f8cff"],["#efa56f","#ba79ff"],["#69dfba","#82a8ff"],["#d48bf0","#f3a36c"],["#64ddec","#7f90ff"]][portraitIndex%14];document.body.dataset.portraitHero="true";const _v2Script=document.querySelector('script[src*="v2.js"]')?.getAttribute('src')||'';const _heroBase=_v2Script.startsWith('..')?'../assets/heroes/':'./assets/heroes/';document.body.style.setProperty("--hero-image",`url('${_heroBase}${key}.png')`);document.body.style.setProperty("--v2-accent",palettes[0]);document.body.style.setProperty("--v2-accent-2",palettes[1])}
  const stored = localStorage.getItem(`theme-${key}`);
  document.body.dataset.theme = stored || (s.light ? "light" : "dark");
  document.body.innerHTML = `<canvas id="v2-canvas" aria-hidden="true"></canvas><div class="v2-noise"></div><div class="v2-progress"></div><div class="v2-shell"><header class="v2-top"><nav class="v2-nav" aria-label="Primary"><a class="v2-brand" href="#home" data-route="home"><span class="v2-mark">${s.name.split(" ").map(x=>x[0]).join("")}</span><span>${s.name}<small class="v2-role">${s.role}</small></span></a><div class="v2-pages">${pages.map(([id,label])=>link(id,label)).join("")}</div><div class="v2-actions"><button class="v2-icon-btn" id="v2-theme" aria-label="Switch color theme"></button><button class="v2-menu" id="v2-menu" aria-label="Open section navigation">${icon("menu")}</button></div></nav></header><main class="v2-main" id="v2-main"></main><footer class="v2-footer"><div class="v2-wrap"><strong>${s.name} · ${s.role}</strong><span>Fictional sample portfolio. All names, roles, metrics, and testimonials are sample content.</span></div></footer></div><aside class="v2-drawer" id="v2-drawer" aria-hidden="true"><div class="v2-drawer-head"><strong>Portfolio sections</strong><button class="v2-icon-btn" id="v2-close" aria-label="Close menu">${icon("close")}</button></div><nav class="v2-drawer-links">${pages.map(([id,label])=>link(id,label)).join("")}</nav></aside>`;
  const main = document.querySelector("#v2-main");
  const drawPage = () => {
    document.title=`${s.name} | ${s.role}`;
    main.innerHTML=`<div class="v2-page">${pages.map(([id])=>`<section class="v2-scroll-section" id="${id}" aria-label="${pages.find(x=>x[0]===id)[1]}">${renderers[id]()}</section>`).join("")}</div>`;
    bindPage();
    const sectionObserver=new IntersectionObserver(entries=>entries.forEach(entry=>{if(entry.isIntersecting){document.querySelectorAll("[data-route]").forEach(a=>a.toggleAttribute("aria-current",a.dataset.route===entry.target.id))}}),{rootMargin:"-35% 0px -55%",threshold:0});
    document.querySelectorAll(".v2-scroll-section").forEach(section=>sectionObserver.observe(section));
  };
  const bindPage = () => {
    const observer = new IntersectionObserver(entries=>entries.forEach(entry=>{if(entry.isIntersecting){entry.target.classList.add("in");observer.unobserve(entry.target)}}),{threshold:.12});
    document.querySelectorAll(".v2-reveal").forEach((el,i)=>{el.style.transitionDelay=`${Math.min(i%4*55,165)}ms`;observer.observe(el)});
    const motionObserver=new IntersectionObserver(entries=>entries.forEach(entry=>entry.target.classList.toggle("motion-live",entry.isIntersecting)),{threshold:.18});
    document.querySelectorAll(".role-motion").forEach(el=>motionObserver.observe(el));
    const cineObserver=new IntersectionObserver(entries=>entries.forEach(entry=>entry.target.classList.toggle("cine-live",entry.isIntersecting)),{threshold:.08});
    document.querySelectorAll(".v2-cinematic").forEach(el=>cineObserver.observe(el));
    const tilt=document.querySelector("[data-tilt]");
    if(tilt && matchMedia("(hover:hover) and (pointer:fine) and (prefers-reduced-motion:no-preference)").matches){tilt.addEventListener("pointermove",e=>{const r=tilt.getBoundingClientRect();tilt.style.setProperty("--tilt-x",`${((e.clientX-r.left)/r.width-.5)*3}deg`);tilt.style.setProperty("--tilt-y",`${((e.clientY-r.top)/r.height-.5)*-3}deg`)});tilt.addEventListener("pointerleave",()=>{tilt.style.setProperty("--tilt-x","0deg");tilt.style.setProperty("--tilt-y","0deg")})}
    const form=document.querySelector("#v2-form");if(form)form.addEventListener("submit",e=>{e.preventDefault();form.querySelector("button").textContent="Message ready to send";document.querySelector("#v2-form-status").textContent="This portfolio demo does not transmit data."});
  };
  document.addEventListener("click",e=>{const a=e.target.closest("[data-route]");if(!a)return;e.preventDefault();document.querySelector(`#${a.dataset.route}`)?.scrollIntoView({behavior:matchMedia("(prefers-reduced-motion: reduce)").matches?"auto":"smooth",block:"start"});drawer.classList.remove("open");drawer.setAttribute("aria-hidden","true")});
  const themeButton=document.querySelector("#v2-theme");
  const setThemeIcon=()=>themeButton.innerHTML=icon(document.body.dataset.theme==="dark"?"sun":"moon");
  themeButton.addEventListener("click",()=>{document.body.dataset.theme=document.body.dataset.theme==="dark"?"light":"dark";localStorage.setItem(`theme-${key}`,document.body.dataset.theme);setThemeIcon()});setThemeIcon();
  const drawer=document.querySelector("#v2-drawer");document.querySelector("#v2-menu").addEventListener("click",()=>{drawer.classList.add("open");drawer.setAttribute("aria-hidden","false");document.querySelector("#v2-close").focus()});document.querySelector("#v2-close").addEventListener("click",()=>{drawer.classList.remove("open");drawer.setAttribute("aria-hidden","true")});
  let cineFrame=0;
  const updateCinematic=()=>{cineFrame=0;const scene=document.querySelector(".v2-cinematic");if(!scene||matchMedia("(prefers-reduced-motion: reduce)").matches)return;const r=scene.getBoundingClientRect(),travel=Math.max(1,scene.offsetHeight-innerHeight),p=Math.max(0,Math.min(1,-r.top/travel)),e=p<.5?2*p*p:1-Math.pow(-2*p+2,2)/2;const art=scene.querySelector(".cine-art"),copy=scene.querySelector(".cine-copy"),visual=scene.querySelector(".cine-role-visual"),beats=[...scene.querySelectorAll(".cine-beats div")],meter=scene.querySelector(".cine-meter i");art.style.transform=`scale(${1+e*.19}) translate3d(0,${e*-4}%,0)`;art.style.filter=`saturate(${1+e*.28}) contrast(${1+e*.12}) brightness(${1-e*.18})`;copy.style.transform=`translate3d(0,${e*-22}vh,0)`;copy.style.opacity=String(Math.max(0,1-p*1.55));visual.style.transform=`translate3d(${(p-.5)*-13}vw,${e*-6}vh,0) scale(${.82+e*.44}) rotate(${(p-.5)*-7}deg)`;visual.style.opacity=String(.32+Math.sin(Math.min(1,p)*Math.PI)*.68);beats.forEach((beat,i)=>{const local=Math.max(0,Math.min(1,(p-i/3)*4));beat.style.opacity=String(.22+local*.78);beat.style.transform=`translate3d(0,${(1-local)*18}px,0)`;beat.classList.toggle("is-active",p>=i/3&&p<(i+1)/3)});meter.style.transform=`scaleX(${p})`;scene.classList.toggle("cine-complete",p>.88)};
  const queueCinematic=()=>{if(!cineFrame)cineFrame=requestAnimationFrame(updateCinematic)};
  addEventListener("scroll",()=>{document.querySelector(".v2-top").classList.toggle("scrolled",scrollY>18);document.querySelector(".v2-progress").style.transform=`scaleX(${scrollY/Math.max(1,document.documentElement.scrollHeight-innerHeight)})`;queueCinematic()},{passive:true});
  if(location.search)history.replaceState(null,"",location.pathname+location.hash);
  drawPage();queueCinematic();
  if(location.hash)requestAnimationFrame(()=>document.querySelector(location.hash)?.scrollIntoView({block:"start"}));

  const canvas=document.querySelector("#v2-canvas"),cx=canvas.getContext("2d",{alpha:true});let particles=[],w=0,h=0,t=0,mouse={x:.65,y:.4};
  const resize=()=>{w=canvas.width=Math.floor(innerWidth*devicePixelRatio);h=canvas.height=Math.floor(innerHeight*devicePixelRatio);canvas.style.width=`${innerWidth}px`;canvas.style.height=`${innerHeight}px`;cx.setTransform(devicePixelRatio,0,0,devicePixelRatio,0,0);particles=Array.from({length:Math.min(100,Math.floor(innerWidth/13))},(_,i)=>({x:Math.random()*innerWidth,y:Math.random()*innerHeight,vx:(Math.random()-.5)*.24,vy:(Math.random()-.5)*.24,r:1+Math.random()*2,phase:i*.7}))};
  const animate=()=>{t+=.008;cx.clearRect(0,0,innerWidth,innerHeight);const style=getComputedStyle(document.body),a=style.getPropertyValue("--v2-accent").trim(),b=style.getPropertyValue("--v2-accent-2").trim();cx.strokeStyle=a;cx.fillStyle=a;cx.lineWidth=1;
    particles.forEach((q,i)=>{q.x=(q.x+q.vx+innerWidth)%innerWidth;q.y=(q.y+q.vy+innerHeight)%innerHeight;const wave=Math.sin(t*2+q.phase);if(["data-scientist","product","designer","analyst"].includes(key))q.y+=wave*.08;cx.globalAlpha=.11+(wave+1)*.03;cx.beginPath();if(key==="analyst")cx.rect(q.x,q.y,Math.max(1,q.r),12+q.r*8);else if(key==="cloud")cx.roundRect(q.x,q.y,8+q.r*4,5+q.r*2,2);else cx.arc(q.x,q.y,q.r,0,Math.PI*2);cx.fill();if(["ai-ml","cloud","fullstack","devops"].includes(key)){particles.slice(i+1,i+6).forEach(n=>{const d=Math.hypot(q.x-n.x,q.y-n.y);if(d<115){cx.globalAlpha=(1-d/115)*.08;cx.beginPath();cx.moveTo(q.x,q.y);cx.lineTo(n.x,n.y);cx.stroke()}})}});
    if(key==="cyber"){cx.save();cx.translate(innerWidth*.78,innerHeight*.42);cx.strokeStyle=b;for(let i=1;i<6;i++){cx.globalAlpha=.08;cx.beginPath();cx.arc(0,0,i*48+Math.sin(t*3)*8,0,Math.PI*2);cx.stroke()}cx.rotate(t);cx.globalAlpha=.15;cx.beginPath();cx.moveTo(0,0);cx.lineTo(280,0);cx.stroke();cx.restore()}
    if(key==="software"){cx.globalAlpha=.08;cx.strokeStyle=b;cx.beginPath();for(let x=0;x<innerWidth;x+=60){const y=innerHeight*.8+Math.sin(x*.012+t*4)*28;cx.lineTo(x,y)}cx.stroke()}
    cx.globalAlpha=1;requestAnimationFrame(animate)};
  addEventListener("resize",resize,{passive:true});addEventListener("pointermove",e=>{mouse.x=e.clientX/innerWidth;mouse.y=e.clientY/innerHeight},{passive:true});resize();if(!matchMedia("(prefers-reduced-motion: reduce)").matches)animate();
})();
